name: Deploy

on:
  push:
    branches: [ "production" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -o futebol-api

    - name: Deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_PATH: ${{ secrets.SERVER_PATH }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts

        # Parar o serviço antes de copiar o binário
        ssh -i private_key.pem $SERVER_USER@$SERVER_HOST <<EOF
          sudo systemctl stop futebol-api.service
          sudo mv /var/www/futebol-api/futebol-api /var/www/futebol-api/futebol-api.old
        EOF
        
        # Copiar o binário para o diretório de destino
        scp -i private_key.pem futebol-api $SERVER_USER@$SERVER_HOST:/var/www/futebol-api/

        # Reiniciar o serviço
        ssh -i private_key.pem $SERVER_USER@$SERVER_HOST <<EOF
          sudo systemctl start futebol-api.service
        EOF
